### ISSUE TITLE
Schematics don't paste at correct location

### ISSUE THREAD

**Issue by Technerder** [CrystalGamesMC/Scaffolding#2] opened 2022-01-03 21:26 UTC
The schematic should be building at/around the area where the schematic was saved from. 

The schematic is saved using WorldEdit on Fabric like so
![image](https://user-images.githubusercontent.com/15988124/147981773-364e50ce-eefc-43bf-9987-3f03b7b103f0.png)

However when the schematic is pasted with `schematic.build(spawnInstance, new Pos(0, 100, 0))`  the schematic is *actually* built with the centre emerald block at `9, 119, 8` instead of `0, 99, 0`

![image](https://user-images.githubusercontent.com/15988124/147982102-3f1705b6-222f-40b2-be90-da590925b96f.png)

![image](https://user-images.githubusercontent.com/15988124/147981999-96a69581-8ac9-44a9-8b20-1eb7f6dc77bc.png)

**Comment by Technerder** [comment] 2022-01-03 21:35
Pasting at `-9, 80, -8` seems to paste it at the correct location

**Comment by LooFifteen** [comment] 2022-01-03 22:13
This is most likely caused by the lack of offset calculation in Scaffolding. I'll look into this when I'm next available to.

Note to self: Sponge has offsets built in but MCEdit requires WorldEdit

**Comment by Technerder** [comment] 2022-01-03 22:15
That's what I thought so too, my PR retrieves the `WEOffsetX`, `WEOffsetY`, and `WEOffsetZ` offsets from the `Metadata` compound, and adds them to the block position.

**Comment by LooFifteen** [comment] 2022-01-03 22:17
I'll add MCEdit support to your PR then get it merged sometime tomorrow (make sure the `Allow contributors to commit`, or something along those lines, box is checked).

**Comment by Technerder** [comment] 2022-01-03 22:19
If you mean the checkbox here then it should be ticked. 
![image](https://user-images.githubusercontent.com/15988124/147986602-0d38efbc-7ea3-4336-b677-127c94b74e4b.png)

**Comment by LooFifteen** [comment] 2022-01-03 22:21
That's the one, thank you very much.

**Comment by Technerder** [comment] 2022-01-03 22:22
No worries, thank you for your swift response :)

**Closed as completed** 2022-01-04 07:45 UTC
